### ISSUE TITLE
IPv4 support in webcam.py

### ISSUE THREAD

**Issue by JustinS-B** [christopherkobayashi/octoprint-stuff#1]
The haproxy.cfg configuration works flawlessly in an IPv4 environment, but your webcam.py is only IPv6 compatible. What do we need to change to enable webcam.py to function in an IPv4 environment please?

Thank you for the haproxy.cfg - it literally saved me days of work as my haproxy config knowledge is terrible

Is it possible to add another argument to webcam.py? Something like --ipv
`parser.add_argument('--ipv', type=int, default=6, help='IP version (default=6)')`

then add some If statements to call ThreadedHTTPServer instead of ThreadedHTTPServerV6 if IPv4 is in use?

Alas, my basic python knowledge isn't enough to add this in without the help of someone who knows what they're doing, as all I get is "network protocol violation" errors.

**Comment by christopherkobayashi** [comment]
Hello Justin,

Thanks for testing!

Have you somehow disabled IPv6 completely, or are running on a non-Linux platform?  I'm asking because (under Linux) binding to :: binds both IPv4 and IPv6 ports on all interfaces.  For example, with webcam.py being called as "/usr/bin/python /usr/local/bin/webcam.py --index 1":

nuskie:~ wileyc$ telnet ${IPV4}  80
Trying ${IPV4}...
Connected to ${IPV4}.
Escape character is '^]'.
^]
telnet> close
Connection closed.
nuskie:~ wileyc$ telnet ${IPV6} 8080
Trying ${IPV6} ...
Connected to ${IPV6}.
Escape character is '^]'.
^]
telnet> close
Connection closed.

Thinking a bit more ... if you have disabled IPv6 or if net.ipv6.bindv6only is set to 1, then binding to IPv6 wouldn't do what we want.  We could autodetect that by looking at the sysctl interface, but that would needlessly complicate what should be a very simple daemon.

I've committed a quick fix that seems to do the right thing.  Let me know if you're still having issues.

**Comment by JustinS-B** [comment]
I'm running octoprint on a Pi3 under Arch Linux, I haven't disabled IPv6, & I'm viewing everything on an Arch Linux PC - usually through Firefox. Your quick fix works perfectly under Chrome, & streams the picam happily, but still generates a "network protocol violation" error under the latest version of Firefox. I'll have a look to see if I can find a quick solution to the Firefox issue, but thank you for the quick fix

**Comment by christopherkobayashi** [comment]
I'm also running under Arch.  Odd that you're seeing different behavior.

That "network protocol violation" error might be Firefox trying to speak HTTPS to a HTTP server.  Might be a good idea to fire up tcpdump and look at what Firefox is sending.

I'll close this issue.  Thanks very much for the feedback!

**Comment by christopherkobayashi** [comment]
I tracked down the issue with Firefox -- it turned out that the boundary separator didn't have an ending newline.  I have no idea why this worked in Chrome.

Anyway, it should be fixed now.  If you can confirm that things work for you, I'll re-close this issue.

**Comment by JustinS-B** [comment]
That completely fixed it, so it is now working perfectly in Firefox.
Thank you, we can definitely now re-close this issue.

**Comment by JustinS-B** [comment]
OK. It worked perfectly if I ran webcam.py from a command line, but when I ran it as a service, it failed with this error:
(scroll to the end for the fix)

```
systemctl start webcam@0

systemctl status webcam@0

webcam@0.service - Octoprint camera daemon
     Loaded: loaded (/etc/systemd/system/webcam@.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2020-12-10 13:13:05 GMT; 7s ago
   Main PID: 20081 (webcam.py)
      Tasks: 1 (limit: 1911)
     CGroup: /system.slice/system-webcam.slice/webcam@0.service
             └─20081 /usr/bin/python /usr/local/bin/webcam.py --index 0

Dec 10 13:13:05 ender systemd[1]: Started Octoprint camera daemon.
Dec 10 13:13:06 ender webcam.py[20081]: [ WARN:0] global /tmp/pip-install-jv2nsxst/opencv-python/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index

```

This is actually caused by a permissions error on /dev/video0 as the user octoprint (called in the service file) doesn't have permissions to view /dev/video0 on my system - because I run a heavily customised system. 

**This was easily fixed by adding the user octoprint to the group video and restarting the service.** This probably isn't a problem for anyone else, but I mention it just in case someone hits this problem, as it has a nice, easy fix.
